### ISSUE TITLE
QQ: dockerize?

### ISSUE THREAD

**Issue by mgaulton** [hillar/vagrant_moloch_bro_suricata#3]
I'm looking for something very much like this but i'd like to be able to run it using docker containers. I'm not that familiar with the vagrant part. Wondering if you have suggestions on how to make this work within docker?

**Comment by hillar** [comment]
bash provision scripts can be converted easily to docker file's

```
apt-get instal -y pkgname -> RUN apt-get instal -y pkgname
```

but see https://docs.vagrantup.com/v2/provisioning/docker.html 

;)

i'm replacing this repo with https://github.com/hillar/CDMCS, but it takes time....
